version: '3'

services:
  apollo-router:
    image: ghcr.io/apollographql/router:v${APOLLO_ROUTER_VERSION}
    container_name: 'apollo-router'
    restart: always
    environment:
      - APOLLO_KEY=${APOLLO_ROUTER_KEY}
      - APOLLO_GRAPH_REF=${APOLLO_ROUTER_GRAPH_REF}
      - APOLLO_SCHEMA_REPORTING=${APOLLO_ROUTER_SCHEMA_REPORTING}
    volumes:
      - ./router.yaml:/dist/config/router.yaml
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
    command:
      [
        '-c',
        'config/router.yaml',
        '-s',
        'schema/supergraph.graphql',
        '--log',
        'info',
      ]
    ports:
      - '4000:4000'
      - '8088:8088'
      - '9090:9090'

  wpgraphql:
    container_name: 'wpgraphql'
    build: ./subgraphs/wpgraphql
    restart: always
    environment:
      - PORT=${SUBGRAPH_WPGRAPHQL_PORT}
      - WPGRAPHQL_URL=${SUBGRAPH_WPGRAPHQL_URL}
