version: '3.8'

services:
  apollo-router:
    image: ghcr.io/apollographql/router:v${APOLLO_ROUTER_VERSION}
    container_name: 'apollo-router'
    environment:
      - WPGRAPHQL_URL=${WPGRAPHQL_URL}
      - APOLLO_KEY=${APOLLO_ROUTER_KEY}
      - APOLLO_GRAPH_REF=${APOLLO_ROUTER_GRAPH_REF}
      - APOLLO_SCHEMA_REPORTING=${APOLLO_ROUTER_SCHEMA_REPORTING}
    volumes:
      - ./router.yaml:/dist/config/router.yaml
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
    command:
      [
        '-c',
        'config/router.yaml',
        '-s',
        'schema/supergraph.graphql',
        '--log',
        'info',
        '--dev',
      ]
    ports:
      - 4000:4000
      - 8088:8088
      - 9090:9090
#   grafana:
#     image: grafana/grafana
#     restart: always
#     environment:
#       GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
#     volumes:
#       - grafana_data:/var/lib/grafana
#       - ./grafana/provisioning/:/etc/grafana/provisioning/
#     env_file:
#       - ./grafana/config.monitoring
#     ports:
#       - 5000:3000
#     depends_on:
#       - apollo-router

# volumes:
#   grafana_data: {}

# wpgraphql:
#   container_name: 'wpgraphql'
#   build: ./subgraphs/wpgraphql
#   environment:
#     - PORT=${SUBGRAPH_WPGRAPHQL_PORT}
#     - WPGRAPHQL_URL=${WPGRAPHQL_URL}
#   ports:
#     - 4001:${SUBGRAPH_WPGRAPHQL_PORT}
